micronaut:
  application:
    name: micronautTodo

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/aj
    username: root
    password: pw
    packages-to-scan:
      - 'com.incubyte'

jpa:
  default:
    properties:
      hibernate:
        ddl-auto: create-drop
        #        hbm2ddl:
        #          auto: update
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.sql'